### ISSUE TITLE
"Not soon" and "Kind of soon" labels are mixed up

### ISSUE THREAD

**Issue by faysvas** [the-collab-lab/tcl-49-smart-shopping-list#32]
The labels for "Not Soon" and "Kind of Soon" are mixed up when you add an item although their values are correct. 
Refer to [issue 4](https://github.com/the-collab-lab/tcl-49-smart-shopping-list/issues/4) to check the correct ordering of the labels.

**Comment by thatgirldorian** [comment]
Hi @faysvas I fixed this in my task (the UI issue for issue 12) and the labels work fine now.
